Repository EnigmaVSSUT/Induction-2023, pull requests merged in 2023-04, with the labels that each got.

#742 web task 1 completed with responsiveness
  Web Development/Task-1/Task Submission/Chinmay priyansu/Web capture_31-3-2023_154718_127.0.0.1.jpeg
  Web Development/Task-1/Task Submission/Chinmay priyansu/index.html
  Web Development/Task-1/Task Submission/Chinmay priyansu/link.txt
  Web Development/Task-1/Task Submission/Chinmay priyansu/photos/IMG-20230304-WA0026.jpg
  Web Development/Task-1/Task Submission/Chinmay priyansu/photos/IMG-20230306-WA0006.jpg
  Web Development/Task-1/Task Submission/Chinmay priyansu/photos/IMG-20230307-WA0009.jpg
  Web Development/Task-1/Task Submission/Chinmay priyansu/photos/pic1.jpg
  Web Development/Task-1/Task Submission/Chinmay priyansu/style.css
Labels: Approved, Fully-responsive

#739 web task 1 completed and changes made
  Open_Source/Task-1/jaydeep.txt
  Web Development/Task-1/Task Submission/Jaydeep Behura/2ce96cbd-e5f1-4673-ad8a-615a7eb98348.jpg
  Web Development/Task-1/Task Submission/Jaydeep Behura/WhatsApp Image 2023-04-03 at 23.15.15 (1).jpeg
  Web Development/Task-1/Task Submission/Jaydeep Behura/WhatsApp Image 2023-04-03 at 23.15.15.jpeg
  Web Development/Task-1/Task Submission/Jaydeep Behura/WhatsApp Image 2023-04-03 at 23.15.16.jpeg
  Web Development/Task-1/Task Submission/Jaydeep Behura/aac0a454-3cc7-496f-92e5-d240026dc56e.jpg
  Web Development/Task-1/Task Submission/Jaydeep Behura/abstract-blue-background-simple-design-for-your-website-free-vector.webp
  Web Development/Task-1/Task Submission/Jaydeep Behura/b4c80a7e-04e9-49c8-8a64-daa5555acff6.jpg
  Web Development/Task-1/Task Submission/Jaydeep Behura/b7a63c26-1e7f-4b03-b91f-7bc385274c84.jpg
  Web Development/Task-1/Task Submission/Jaydeep Behura/index.html
  Web Development/Task-1/Task Submission/Jaydeep Behura/index2.html
  Web Development/Task-1/Task Submission/Jaydeep Behura/istockphoto-1390647151-170667a.jpg
  Web Development/Task-1/Task Submission/Jaydeep Behura/link.txt
  Web Development/Task-1/Task Submission/Jaydeep Behura/styles.css
Labels: Approved, Fully-responsive

#736 web dev task 1 completed
  Web Development/Task-1/Task Submission/Nilesh Mishra/2.jpg
  Web Development/Task-1/Task Submission/Nilesh Mishra/3.jpg
  Web Development/Task-1/Task Submission/Nilesh Mishra/A.jpg
  Web Development/Task-1/Task Submission/Nilesh Mishra/G.jpg
  Web Development/Task-1/Task Submission/Nilesh Mishra/Nilesh.jpg
  Web Development/Task-1/Task Submission/Nilesh Mishra/T.jpg
  Web Development/Task-1/Task Submission/Nilesh Mishra/index.html
  Web Development/Task-1/Task Submission/Nilesh Mishra/link.txt
  Web Development/Task-1/Task Submission/Nilesh Mishra/screenshot.png
  Web Development/Task-1/Task Submission/Nilesh Mishra/style.css
Labels: Approved, Fully-responsive

#732 web dev task 1 added responsiveness
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/Screenshot.png
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/img.jpg
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/img1.jpg
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/img2.jpg
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/img3.jpeg
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/img4.png
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/img5.jpeg
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/index.html
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/link.txt
  Web Development/Task-1/Task Submission/Gouri Shankar Kishan/style.css
Labels: Approved, Fully-responsive

#730 Completed web task 1, added responsiveness
  Web Development/Task-1/Task Submission/Harish Sahoo/1.jpg
  Web Development/Task-1/Task Submission/Harish Sahoo/127.0.0.1_5500_Harish.html.png
  Web Development/Task-1/Task Submission/Harish Sahoo/2.jpg
  Web Development/Task-1/Task Submission/Harish Sahoo/3.jpg
  Web Development/Task-1/Task Submission/Harish Sahoo/Cooking.webp
  Web Development/Task-1/Task Submission/Harish Sahoo/Garden.jpg
  Web Development/Task-1/Task Submission/Harish Sahoo/Harish.jpg
  Web Development/Task-1/Task Submission/Harish Sahoo/Travel.jpg
  Web Development/Task-1/Task Submission/Harish Sahoo/index.html
  Web Development/Task-1/Task Submission/Harish Sahoo/link.txt
  Web Development/Task-1/Task Submission/Harish Sahoo/style.css
Labels: Approved, Fully-responsive

#728 completed web task 1 added responsiveness
  Web Development/Task-1/Task Submission/Nihar ranjan behera/ai.jpg
  Web Development/Task-1/Task Submission/Nihar ranjan behera/image1
  Web Development/Task-1/Task Submission/Nihar ranjan behera/image2
  Web Development/Task-1/Task Submission/Nihar ranjan behera/index.html
  Web Development/Task-1/Task Submission/Nihar ranjan behera/link.text
  Web Development/Task-1/Task Submission/Nihar ranjan behera/nil.jpg
  Web Development/Task-1/Task Submission/Nihar ranjan behera/pi.jpg
  Web Development/Task-1/Task Submission/Nihar ranjan behera/ss.png
  Web Development/Task-1/Task Submission/Nihar ranjan behera/style.css
Labels: Approved, Fully-responsive

#727 web dev task 1 complete
  Web Development/Task-1/Task Submission/Ishika Pradhan/index.html.html
  Web Development/Task-1/Task Submission/Ishika Pradhan/ishika23.c
  Web Development/Task-1/Task Submission/Ishika Pradhan/rain.jpeg
  Web Development/Task-1/Task Submission/Ishika Pradhan/rainbow.jpeg
  Web Development/Task-1/Task Submission/Ishika Pradhan/river.jpeg
  Web Development/Task-1/Task Submission/Ishika Pradhan/sunflower.jpeg
Labels: Approved, Fully-responsive

#723 Web Dev Task 1 Completed!
  Web Development/Task-1/Task Submission/Ankita Samantaray/.vscode/launch.json
  Web Development/Task-1/Task Submission/Ankita Samantaray/Screenshot.png
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/background1.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/brave.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/cat.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/github.png
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/gmail.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/instagram.png
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/k1.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/k2.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/ll.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/mo.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/music.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/p.png
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/rere.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/rr.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/x.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/y.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/images/yy.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/index.html
  Web Development/Task-1/Task Submission/Ankita Samantaray/link.txt
  Web Development/Task-1/Task Submission/Ankita Samantaray/sample.jpg
  Web Development/Task-1/Task Submission/Ankita Samantaray/style.css
Labels: Approved, Fully-responsive

#722 Web Dev Task Completed
  Open_Source/Task-1/Priyanka_Sabat.txt
  Web Development/Task-1/Task Submission/Priyanka Sabat/index.html
  Web Development/Task-1/Task Submission/Priyanka Sabat/link.txt
  Web Development/Task-1/Task Submission/Priyanka Sabat/photo 1.jpg
  Web Development/Task-1/Task Submission/Priyanka Sabat/photo 2.jpg
  Web Development/Task-1/Task Submission/Priyanka Sabat/screenshot.jpeg
  Web Development/Task-1/Task Submission/Priyanka Sabat/style.css
Labels: Approved, Fully-responsive

#718 web dev task 1 changes done
  Web Development/Task-1/Task Submission/Sagar Nayak/d1.jfif
  Web Development/Task-1/Task Submission/Sagar Nayak/d2.jfif
  Web Development/Task-1/Task Submission/Sagar Nayak/d3.jfif
  Web Development/Task-1/Task Submission/Sagar Nayak/d4.jfif
  Web Development/Task-1/Task Submission/Sagar Nayak/d5.jpg
  Web Development/Task-1/Task Submission/Sagar Nayak/d6.jpg
  Web Development/Task-1/Task Submission/Sagar Nayak/download1.png
  Web Development/Task-1/Task Submission/Sagar Nayak/index.html
  Web Development/Task-1/Task Submission/Sagar Nayak/link.txt
  Web Development/Task-1/Task Submission/Sagar Nayak/screenshot.png
  Web Development/Task-1/Task Submission/Sagar Nayak/style.css
Labels: Approved, Fully-responsive

#712 web dev task completed
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/Port.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a1.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a10.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a10.webp
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a11.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a2.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a3.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a4.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a5.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a6.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a7.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a8.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/a9.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/b1.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/b2.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/b3.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/b4.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/bg.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/cleanl.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/index.html
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/link.txt
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/port2.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/pxfuel (1).jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/screenshot.png
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/skyl.jpg
  Web Development/Task-1/Task Submission/Nayak Ronak Ashish/style.css
Labels: Approved, Fully-responsive

#701 Web Development
  Web Development/Task-1/Task Submission/Komal_Goel/index.html
  Web Development/Task-1/Task Submission/Komal_Goel/screenshot/screenshot.png
  Web Development/Task-1/Task Submission/Komal_Goel/style.css
  Web Development/Task-1/Task Submission/Komal_Goel/weblink.txt
Labels: Approved, Fully-responsive

#697 Web development task-1 completed
  Web Development/Task-1/Task Submission/Nikita Pradhan/gallery1.jpg
  Web Development/Task-1/Task Submission/Nikita Pradhan/gallery2.jpg
  Web Development/Task-1/Task Submission/Nikita Pradhan/gallery3.jpg
  Web Development/Task-1/Task Submission/Nikita Pradhan/hobby.png
  Web Development/Task-1/Task Submission/Nikita Pradhan/index.html
  Web Development/Task-1/Task Submission/Nikita Pradhan/link.txt
  Web Development/Task-1/Task Submission/Nikita Pradhan/nikita.jpg
  Web Development/Task-1/Task Submission/Nikita Pradhan/output/n.exe
  Web Development/Task-1/Task Submission/Nikita Pradhan/screenshot-nikitap1103.github.io-2023.04.02-17_08_43.png
  Web Development/Task-1/Task Submission/Nikita Pradhan/style.css
Labels: Approved, Fully-responsive

#696 web dev task 1
  Web Development/Task-1/Task Submission/Amir_Chand/Screenshot 2023-04-02 000004.png
  Web Development/Task-1/Task Submission/Amir_Chand/github.png
  Web Development/Task-1/Task Submission/Amir_Chand/img2.jpeg
  Web Development/Task-1/Task Submission/Amir_Chand/img3.jpeg
  Web Development/Task-1/Task Submission/Amir_Chand/img4.jpeg
  Web Development/Task-1/Task Submission/Amir_Chand/index.html
  Web Development/Task-1/Task Submission/Amir_Chand/insta.png
  Web Development/Task-1/Task Submission/Amir_Chand/link.txt
  Web Development/Task-1/Task Submission/Amir_Chand/linkedin.png
  Web Development/Task-1/Task Submission/Amir_Chand/post.jpg
  Web Development/Task-1/Task Submission/Amir_Chand/task-1.css
Labels: Approved, Fully-responsive

#694 web dev task-1 submitted
  Web Development/Task-1/Task Submission/Kaushik Dash/images/Instagram.png
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g1.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g2.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g3.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g4.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g5.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g6.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g7.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/g8.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/images/gmail.png
  Web Development/Task-1/Task Submission/Kaushik Dash/images/linkedin.png
  Web Development/Task-1/Task Submission/Kaushik Dash/images/profile.jpg
  Web Development/Task-1/Task Submission/Kaushik Dash/index.html
  Web Development/Task-1/Task Submission/Kaushik Dash/link.txt
  Web Development/Task-1/Task Submission/Kaushik Dash/screenshot.png
  Web Development/Task-1/Task Submission/Kaushik Dash/style.css
Labels: Approved, Awesome, Fully-responsive

#686 web dev task-1 completed
  Web Development/Task-1/Task Submission/Ashutosh Maharana/Screenshot (4).png
  Web Development/Task-1/Task Submission/Ashutosh Maharana/ashu about.jpg
  Web Development/Task-1/Task Submission/Ashutosh Maharana/ashu gallery 2.jpg
  Web Development/Task-1/Task Submission/Ashutosh Maharana/github.png
  Web Development/Task-1/Task Submission/Ashutosh Maharana/index.html
  Web Development/Task-1/Task Submission/Ashutosh Maharana/insta.png
  Web Development/Task-1/Task Submission/Ashutosh Maharana/link.txt
  Web Development/Task-1/Task Submission/Ashutosh Maharana/linkedin.png
  Web Development/Task-1/Task Submission/Ashutosh Maharana/mit.jpg
  Web Development/Task-1/Task Submission/Ashutosh Maharana/style.css
  Web Development/Task-1/Task Submission/Ashutosh Maharana/travelling.jpg
Labels: Approved, Fully-responsive

#685 web dev task 1 completed
  Web Development/Task-1/Task Submission/Ritik Pingua/images/art.jpg
  Web Development/Task-1/Task Submission/Ritik Pingua/images/art1.jpg
  Web Development/Task-1/Task Submission/Ritik Pingua/images/gallery.jpg
  Web Development/Task-1/Task Submission/Ritik Pingua/images/insta.jpg
  Web Development/Task-1/Task Submission/Ritik Pingua/images/mail.png
  Web Development/Task-1/Task Submission/Ritik Pingua/images/profile.jpg
  Web Development/Task-1/Task Submission/Ritik Pingua/index.html
  Web Development/Task-1/Task Submission/Ritik Pingua/link.txt
  Web Development/Task-1/Task Submission/Ritik Pingua/screenshot 2.jpg
  Web Development/Task-1/Task Submission/Ritik Pingua/style.css
Labels: Approved, Fully-responsive

#676 web dev task 1 completed
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/book_pic.jpg
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/gmail.jpeg
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/index.html
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/linked_in.png
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/mail.txt
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/me.jpg
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/pic1.jpg
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/pic2.jpg
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/pic3.jpg
  Web Development/Task-1/Task Submission/Shreeti Mohapatra/style.css
Labels: Approved, Fully-responsive

#671 web dev task1 completed
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/img/adelin-preda--tOr_T4qTpQ-unsplash.jpg
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/img/backgrund.jpg
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/img/bk3.jpg
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/img/myimg.png
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/img/myimg1.png
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/index.html
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/link.txt
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/screenshot/Screenshot 2023-04-01 210223.png
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/screenshot/Screenshot 2023-04-01 210343.png
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/screenshot/Screenshot 2023-04-01 210420.png
  Web Development/Task-1/Task Submission/PRATYUSH PANDA/style.css
Labels: Approved, Fully-responsive

#669 web dev task 1
  Open_Source/Task-1/Rupali_Pradhan.txt
  Web Development/Task-1/Task Submission/Rupali_Pradhan/Screenshot (2).png
  Web Development/Task-1/Task Submission/Rupali_Pradhan/Screenshot (3).png
  Web Development/Task-1/Task Submission/Rupali_Pradhan/index.html
  Web Development/Task-1/Task Submission/Rupali_Pradhan/link.txt
  Web Development/Task-1/Task Submission/Rupali_Pradhan/photo-1454372182658-c712e4c5a1db.jpg
  Web Development/Task-1/Task Submission/Rupali_Pradhan/style.css
Labels: Approved, Fully-responsive

#668 web dev task-1 completed
  Web Development/Task-1/Task Submission/Goutam Nayak/bg2.jpg
  Web Development/Task-1/Task Submission/Goutam Nayak/github.png
  Web Development/Task-1/Task Submission/Goutam Nayak/goutam45.jpg
  Web Development/Task-1/Task Submission/Goutam Nayak/index.html
  Web Development/Task-1/Task Submission/Goutam Nayak/insta.png
  Web Development/Task-1/Task Submission/Goutam Nayak/link.txt
  Web Development/Task-1/Task Submission/Goutam Nayak/linkedin.png
  Web Development/Task-1/Task Submission/Goutam Nayak/one.jpg
  Web Development/Task-1/Task Submission/Goutam Nayak/screenshot.jpg
  Web Development/Task-1/Task Submission/Goutam Nayak/style.css
  Web Development/Task-1/Task Submission/Goutam Nayak/three.jpg
  Web Development/Task-1/Task Submission/Goutam Nayak/two.jpg
Labels: Approved, Fully-responsive

#660 web task 1 completed
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/WhatsApp Image 2023-03-31 at 12.19.31.jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/jason-charters-IorqsMssQH0-unsplash (1).jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/mohammad-rahmani-N5bT5RctFZ8-unsplash.jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/sven-kucinic-Z0KjmjxUsKs-unsplash.jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/w1.jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/w2.jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/images/w3.jpg
  Web Development/Task-1/Task Submission/LaxmanBeshra/index.html
  Web Development/Task-1/Task Submission/LaxmanBeshra/link.txt
  Web Development/Task-1/Task Submission/LaxmanBeshra/screenshot (2).png
  Web Development/Task-1/Task Submission/LaxmanBeshra/style.css
Labels: Approved, Fully-responsive

#655 webdev task 1 completed
  Web Development/Task-1/Task Submission/Kritika Sureka/The-Meshroom.ttf
  Web Development/Task-1/Task Submission/Kritika Sureka/images/img5.png
  Web Development/Task-1/Task Submission/Kritika Sureka/images/img6.png
  Web Development/Task-1/Task Submission/Kritika Sureka/images/img7.jpeg
  Web Development/Task-1/Task Submission/Kritika Sureka/index.html
  Web Development/Task-1/Task Submission/Kritika Sureka/link.txt
  Web Development/Task-1/Task Submission/Kritika Sureka/screenshot/Screenshot (20).png
  Web Development/Task-1/Task Submission/Kritika Sureka/screenshot/Screenshot (21).png
  Web Development/Task-1/Task Submission/Kritika Sureka/style.css
Labels: Approved, Fully-responsive

#652 Updated Files for change requested label
  Web Development/Task-1/Task Submission/Naren Pradhan/CSS/styles.css
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/Discord.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/codechef.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/github.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/gmail.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/instagram.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/linkedin.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Icons/twitter.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/2652652.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/7af559cb05e3678bbf7ddde3f643df91.jpeg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/8241350 resize.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/8241350.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/8241350.webp
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/Group 5.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/Group 6.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/HD-wallpaper-harry-potter-expecto-patronum-gryffindor-harry-potter-hp-movie-potterhead.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/HarryPotter-ov4z.ttf
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/HermioneGranger_PM_B4C28M1_HermioneOpeningHateMailOwls.Moment.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/HermioneGranger_PM_B4C28M1_HermioneOpeningHateMailOwls.Moment.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/JimNightshade-Regular.ttf
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/MinervaMcGonagall_PM_B1C7M2_HarryPotterBeingSortedInGreatHall_Moment.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/cxeimwflyo881.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/cxeimwflyo881.webp
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/harry-potter-owl-drawing-witch-hd-wallpaper-preview.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/octocat-github.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/scenes-from-harry-potter-to-help-with-descriptive-work-in-your-class-castle-descriptions.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/static-assets-upload2531935392873983210.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/static-assets-upload2531935392873983210.webp
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/uxia-lovegood-hp-patronus-min.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Images/wallpaperflare.com_wallpaper.jpg
  Web Development/Task-1/Task Submission/Naren Pradhan/Screenshots/full page.jpeg
  Web Development/Task-1/Task Submission/Naren Pradhan/Screenshots/page 1.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Screenshots/page 2.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Screenshots/page 3.png
  Web Development/Task-1/Task Submission/Naren Pradhan/Screenshots/page 4.png
  Web Development/Task-1/Task Submission/Naren Pradhan/index.html
  Web Development/Task-1/Task Submission/Naren Pradhan/link.txt
Labels: Approved, Fully-responsive

#645 web dev task 1 completed
  Web Development/Task-1/Task Submission/ashutosh panigrahi/Screenshot.png
  Web Development/Task-1/Task Submission/ashutosh panigrahi/bg1.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/coding1.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/git.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/index.html
  Web Development/Task-1/Task Submission/ashutosh panigrahi/insta1.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/link.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/link.txt
  Web Development/Task-1/Task Submission/ashutosh panigrahi/mail.svg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/open.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/photo.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/picture1.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/picture3.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/picture5.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/picture6.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/profile.jpg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/programing.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/standup.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/style.css
  Web Development/Task-1/Task Submission/ashutosh panigrahi/tweet1.jpeg
  Web Development/Task-1/Task Submission/ashutosh panigrahi/web.jpg
Labels: Approved, Fully-responsive

#642 web dev task 1 completed
  Open_Source/Task-2/Ananya Pati.txt
  Web Development/Task-1/Task Submission/ANANYA PATI/aimexp.html
  Web Development/Task-1/Task Submission/ANANYA PATI/bg.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/gallerybg.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/galleryexp.html
  Web Development/Task-1/Task Submission/ANANYA PATI/hobbiesblur.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/index.html
  Web Development/Task-1/Task Submission/ANANYA PATI/interestsexp.html
  Web Development/Task-1/Task Submission/ANANYA PATI/jamshedpur.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/link.txt
  Web Development/Task-1/Task Submission/ANANYA PATI/mbm.html
  Web Development/Task-1/Task Submission/ANANYA PATI/mbmbg.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/myphoto2.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/myself.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/oldagehome.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/orphanage.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/pic.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/pic3.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/pic4.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/pic5.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/pic6.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/picx1.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/picx2.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/picx3.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/picx4.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/picx5.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/picx6.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/screenshot.png
  Web Development/Task-1/Task Submission/ANANYA PATI/speech.jpg
  Web Development/Task-1/Task Submission/ANANYA PATI/style1.css
  Web Development/Task-1/Task Submission/ANANYA PATI/style3exp.css
  Web Development/Task-1/Task Submission/ANANYA PATI/style4exp.css
  Web Development/Task-1/Task Submission/ANANYA PATI/style5exp.css
  Web Development/Task-1/Task Submission/ANANYA PATI/stylef.css
Labels: Approved, Awesome, Fully-responsive

#641 web dev task 1 completed
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/Link.txt
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/etdt.jpeg
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/flowers.jpg
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/guduli.jpg
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/index.html
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/me.jpg
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/screenshot.png
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/sky.jpg
  Web Development/Task-1/Task Submission/Adyasha Pattanayak/style.css
Labels: Approved, Fully-responsive

#635 web task completed
  Web Development/Task-1/Task Submission/Shreya_Bastia/Screenshot1.png
  Web Development/Task-1/Task Submission/Shreya_Bastia/images.jpg
  Web Development/Task-1/Task Submission/Shreya_Bastia/index.html
  Web Development/Task-1/Task Submission/Shreya_Bastia/retro.jpg
  Web Development/Task-1/Task Submission/Shreya_Bastia/scenery.jpg
  Web Development/Task-1/Task Submission/Shreya_Bastia/spy.jpg
  Web Development/Task-1/Task Submission/Shreya_Bastia/style.css
  Web Development/Task-1/Task Submission/Shreya_Bastia/violet.jpg
  Web Development/Task-1/Task Submission/Shreya_Bastia/web.txt.txt
Labels: Approved, Fully-responsive

#633 git web task 1 completed
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/Images/dark.jpg
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/Images/index.html
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/Images/priyanka in beach.jfif
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/Images/priyanka.jpg
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/Images/style.css
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/Screenshot 2023-04-03 at 22-29-28 PRIYANKA padhy.png
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/css/style.css
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/html/AIM.jpg
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/html/dark.jpg
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/html/index.html
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/html/priyanka.html
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/html/priyanka.jpg
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/html/style.css
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/index.html
  Web Development/Task-1/Task Submission/priyanka padhy - Copy/link.txt
Labels: Approved, Fully-responsive

#629 web task completed
  Web Development/Task-1/Task Submission/Archana_Swain/360_F_241674902_1i8NSWE483IGlRkPPvRWWZuLTFBnqIWh.jpg
  Web Development/Task-1/Task Submission/Archana_Swain/Facebook_icon.svg.webp
  Web Development/Task-1/Task Submission/Archana_Swain/Screenshot (10).png
  Web Development/Task-1/Task Submission/Archana_Swain/Screenshot (11).png
  Web Development/Task-1/Task Submission/Archana_Swain/Screenshot (12).png
  Web Development/Task-1/Task Submission/Archana_Swain/Screenshot (9).png
  Web Development/Task-1/Task Submission/Archana_Swain/download (1).png
  Web Development/Task-1/Task Submission/Archana_Swain/download (2) - Copy.png
  Web Development/Task-1/Task Submission/Archana_Swain/download.jpg
  Web Development/Task-1/Task Submission/Archana_Swain/download.png
  Web Development/Task-1/Task Submission/Archana_Swain/images.jpg
  Web Development/Task-1/Task Submission/Archana_Swain/index.html
  Web Development/Task-1/Task Submission/Archana_Swain/sky1.jpg
  Web Development/Task-1/Task Submission/Archana_Swain/style.css
  Web Development/Task-1/Task Submission/Archana_Swain/web.txt.txt
Labels: Approved, Fully-responsive

#624 Web Task-1 Completed
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/Screenshot (14).png
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/bimg1.jpg
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/dslr.jpg
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/hksp.png
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/index.html
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/marvel.jpg
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/screenshot.png
  Web Development/Task-1/Task Submission/A Harekrushna Nayak/style.css
Labels: Approved, Fully-responsive

#654 completed web task 1
  Web Development/Task-1/Task Submission/Banty Kumar Das/Pictures/Intrest.jpeg
  Web Development/Task-1/Task Submission/Banty Kumar Das/Pictures/background.jpg
  Web Development/Task-1/Task Submission/Banty Kumar Das/Pictures/education.png
  Web Development/Task-1/Task Submission/Banty Kumar Das/Pictures/me.jpg
  Web Development/Task-1/Task Submission/Banty Kumar Das/Pictures/skills.jpeg
  Web Development/Task-1/Task Submission/Banty Kumar Das/css.css
  Web Development/Task-1/Task Submission/Banty Kumar Das/index.html
  Web Development/Task-1/Task Submission/Banty Kumar Das/link.txt
  Web Development/Task-1/Task Submission/Banty Kumar Das/screenshot.png
Labels: Approved, Fully-responsive

#745 Completed web task 1, added responsiveness
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/art.jpg
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/bgim1.jpg
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/gmail-logo.png
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/ig-logo2.png
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/linkedin-logo.png
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/me.jpg
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/paint.jpg
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/screenshot1.png
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/vssut.jpg
  Web Development/Task-1/Task Submission/Saleena Das/Pictures/wall-e.jpg
  Web Development/Task-1/Task Submission/Saleena Das/index.html
  Web Development/Task-1/Task Submission/Saleena Das/link.txt
  Web Development/Task-1/Task Submission/Saleena Das/screenshot.png
  Web Development/Task-1/Task Submission/Saleena Das/style.css
Labels: Approved, Fully-responsive

#741 web dev task 1 completed
  Web Development/Task-1/Task Submission/Sangram Ranasingh/Travel.jpg
  Web Development/Task-1/Task Submission/Sangram Ranasingh/cooking.jpg
  Web Development/Task-1/Task Submission/Sangram Ranasingh/index.html
  Web Development/Task-1/Task Submission/Sangram Ranasingh/link.txt
  Web Development/Task-1/Task Submission/Sangram Ranasingh/profile.jpg
  Web Development/Task-1/Task Submission/Sangram Ranasingh/screenshot.png
  Web Development/Task-1/Task Submission/Sangram Ranasingh/style.css
  Web Development/Task-1/Task Submission/Sangram Ranasingh/travelling.jpg
  Web Development/Task-1/Task Submission/Sangram Ranasingh/watching movies.jpeg
  Web Development/Task-1/Task Submission/Sangram Ranasingh/waterfall.jpg
Labels: Approved, Fully-responsive

#675 web task completed
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/Screenshot 1.png
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/Screenshot 2.png
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/Screenshot 3.png
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/Screenshot4.png
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/image3.jpg
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/img2.jpg
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/index.html
  Web Development/Task-1/Task Submission/Subhalaxmi_Nayak/web1.txt.txt
Labels: Approved, Fully-responsive

#612 web dev task 1 completed
  Web development/task-1/Task submission/Abinash Barick/README.md
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_1.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_2.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_3.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_4.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_5.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_6.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_7.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_8.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/gal_img_9.jpg
  Web development/task-1/Task submission/Abinash Barick/assets/github-sign.png
  Web development/task-1/Task submission/Abinash Barick/assets/gmail.png
  Web development/task-1/Task submission/Abinash Barick/assets/instagram.png
  Web development/task-1/Task submission/Abinash Barick/assets/profile.jpg
  Web development/task-1/Task submission/Abinash Barick/contact.html
  Web development/task-1/Task submission/Abinash Barick/gallery.html
  Web development/task-1/Task submission/Abinash Barick/index.html
  Web development/task-1/Task submission/Abinash Barick/intrest.html
  Web development/task-1/Task submission/Abinash Barick/link.txt
  Web development/task-1/Task submission/Abinash Barick/screenshot.png
  Web development/task-1/Task submission/Abinash Barick/style.css
Labels: Approved, Fully-responsive

#611 webdev task 1 completed
  Web Development/Task-1/Task Submission/Kajal Nayak/Screenshot.png
  Web Development/Task-1/Task Submission/Kajal Nayak/images/gallery1.jpeg
  Web Development/Task-1/Task Submission/Kajal Nayak/images/gallery2.jpeg
  Web Development/Task-1/Task Submission/Kajal Nayak/images/gallery3.jpeg
  Web Development/Task-1/Task Submission/Kajal Nayak/images/intpic.jpeg
  Web Development/Task-1/Task Submission/Kajal Nayak/images/mypic.jpeg
  Web Development/Task-1/Task Submission/Kajal Nayak/index.html
  Web Development/Task-1/Task Submission/Kajal Nayak/link.txt
  Web Development/Task-1/Task Submission/Kajal Nayak/style.css
Labels: Approved, Fully-responsive

#607 task completed
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/AI.jpeg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/ANIMAL_LOVER.jpg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/CAT.jpg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/CAT2.jpg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/GAMING.jpg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/ML.jpeg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/PHOTOGRAPHY.jpeg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/UI_UX.png
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/images/ui-ux.jpg
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/index.html
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/link.txt
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/screenshot.png
  Web Development/Task-1/Task Submission/KUSHAL MEHTA/style.css
Labels: Approved, Fully-responsive

#602 completed web task 1
  Web Development/Task-1/Task Submission/SagarSatapathy/assets/anime.jpg
  Web Development/Task-1/Task Submission/SagarSatapathy/assets/bground.jpg
  Web Development/Task-1/Task Submission/SagarSatapathy/assets/drawing.jpg
  Web Development/Task-1/Task Submission/SagarSatapathy/assets/games.jpg
  Web Development/Task-1/Task Submission/SagarSatapathy/assets/sagarspt01.jpg
  Web Development/Task-1/Task Submission/SagarSatapathy/index.html
  Web Development/Task-1/Task Submission/SagarSatapathy/link.txt
  Web Development/Task-1/Task Submission/SagarSatapathy/screnshot.png
  Web Development/Task-1/Task Submission/SagarSatapathy/style.css
Labels: Approved, Fully-responsive

#597 Completed Web Task 1
  Web Development/Task-1/Task Submission/Swastik Mishra/BGP.jpg
  Web Development/Task-1/Task Submission/Swastik Mishra/Complete Web Development Task1.txt
  Web Development/Task-1/Task Submission/Swastik Mishra/Index.html
  Web Development/Task-1/Task Submission/Swastik Mishra/Index2.html
  Web Development/Task-1/Task Submission/Swastik Mishra/WhatsApp Image 2023-03-31 at 18.19.38.jpeg
  Web Development/Task-1/Task Submission/Swastik Mishra/WhatsApp Image 2023-03-31 at 18.19.42.jpeg
  Web Development/Task-1/Task Submission/Swastik Mishra/WhatsApp Image 2023-03-31 at 18.19.44 (1).jpeg
  Web Development/Task-1/Task Submission/Swastik Mishra/WhatsApp Image 2023-03-31 at 18.19.44 (2).jpeg
  Web Development/Task-1/Task Submission/Swastik Mishra/WhatsApp Image 2023-03-31 at 18.19.44.jpeg
  Web Development/Task-1/Task Submission/Swastik Mishra/WhatsApp Image 2023-03-31 at 18.19.58.jpeg
  Web Development/Task-1/Task Submission/Swastik Mishra/farewell.jpg
  Web Development/Task-1/Task Submission/Swastik Mishra/index.html
  Web Development/Task-1/Task Submission/Swastik Mishra/index2.html
  Web Development/Task-1/Task Submission/Swastik Mishra/style.css
Labels: Approved, Fully-responsive

#591 web task 1 completed
  Web Development/Task-1/Task Submission/Sruti S Kar/code.jpg
  Web Development/Task-1/Task Submission/Sruti S Kar/css/style.css
  Web Development/Task-1/Task Submission/Sruti S Kar/index.html
  Web Development/Task-1/Task Submission/Sruti S Kar/link.txt
  Web Development/Task-1/Task Submission/Sruti S Kar/web.jpg
Labels: Approved, Fully-responsive

#585 web dev task 1 completed
  Web Development/Task-1/Task Submission/Satviki Pradhan/css/css/sstyle.css
  Web Development/Task-1/Task Submission/Satviki Pradhan/css/css/style.css
  Web Development/Task-1/Task Submission/Satviki Pradhan/images/Badminton.jpg
  Web Development/Task-1/Task Submission/Satviki Pradhan/images/Baking.jpg
  Web Development/Task-1/Task Submission/Satviki Pradhan/images/Reading.jpg
  Web Development/Task-1/Task Submission/Satviki Pradhan/images/Travelling.jpg
  Web Development/Task-1/Task Submission/Satviki Pradhan/images/myimage.jpg
  Web Development/Task-1/Task Submission/Satviki Pradhan/index.html
  Web Development/Task-1/Task Submission/Satviki Pradhan/link.txt
  Web Development/Task-1/Task Submission/Satviki Pradhan/screenshot.png
Labels: Approved, Fully-responsive

#581 webdev task 1 completed
  WebDevelopement/Screenshot.png
  WebDevelopement/images/coding.jpg
  WebDevelopement/images/cricket.jpg
  WebDevelopement/images/esports.jpg
  WebDevelopement/images/prof.jpg
  WebDevelopement/images/trading.jpg
  WebDevelopement/index.html
  WebDevelopement/link.txt
  WebDevelopement/style.css
Labels: Approved, Fully-responsive

#574 Web Development Task 1 Completed
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/BIMG4.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/Bimg3.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/Pic1.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/Pic3.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/Pic4.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/Pic6.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/Pictures/pic8.jpg
  Web Development/Task-1/Task Submission/Animesh Pattnaik/index.html
  Web Development/Task-1/Task Submission/Animesh Pattnaik/link.txt
  Web Development/Task-1/Task Submission/Animesh Pattnaik/screenshot.png
  Web Development/Task-1/Task Submission/Animesh Pattnaik/style.css
Labels: Approved, Fully-responsive

#575 c
  Web Development/Task-1/Task Submission/Ananya Mohapatra/index.html
  Web Development/Task-1/Task Submission/Ananya Mohapatra/style.css
  Web Development/Task-1/Task Submission/Arman Singh/coding.jpeg
  Web Development/Task-1/Task Submission/Arman Singh/cricket.jpg
  Web Development/Task-1/Task Submission/Arman Singh/gmail.png
  Web Development/Task-1/Task Submission/Arman Singh/index.html
  Web Development/Task-1/Task Submission/Arman Singh/instagram.png
  Web Development/Task-1/Task Submission/Arman Singh/link.txt
  Web Development/Task-1/Task Submission/Arman Singh/photo.jpg
  Web Development/Task-1/Task Submission/Arman Singh/photo1.jpg
  Web Development/Task-1/Task Submission/Arman Singh/photo2.jpg
  Web Development/Task-1/Task Submission/Arman Singh/screenshot.png
  Web Development/Task-1/Task Submission/Arman Singh/style.css
  Web Development/Task-1/Task Submission/Arman Singh/twitter.png
Labels: Approved, Fully-responsive

#573 Git
  Open_Source/Task-1/Yashika_Sharma.txt
  Web Development/Task-1/Task Submission/Yashika Sharma/index.html
  Web Development/Task-1/Task Submission/Yashika Sharma/insta.png
  Web Development/Task-1/Task Submission/Yashika Sharma/link.txt
  Web Development/Task-1/Task Submission/Yashika Sharma/linkedin.png
  Web Development/Task-1/Task Submission/Yashika Sharma/mail.png
  Web Development/Task-1/Task Submission/Yashika Sharma/pic1.jpg
  Web Development/Task-1/Task Submission/Yashika Sharma/screenshot2.png
  Web Development/Task-1/Task Submission/Yashika Sharma/style.css
Labels: Approved, Fully-responsive

#569 web task 1 completed
  Web Development/Task-1/Task Submission/Diya Bhagat/Hobbies.jpg
  Web Development/Task-1/Task Submission/Diya Bhagat/ProfileImage.jpg
  Web Development/Task-1/Task Submission/Diya Bhagat/index.html
  Web Development/Task-1/Task Submission/Diya Bhagat/screenshot.png
Labels: Approved, Awesome, Fully-responsive

#562 web developement task 1 cpmpleted
  Web Development/Task-1/Task Submission/Manasa Mohapatra/index.html
  Web Development/Task-1/Task Submission/Manasa Mohapatra/mine.png
  Web Development/Task-1/Task Submission/Manasa Mohapatra/myimage1.png
  Web Development/Task-1/Task Submission/Manasa Mohapatra/screenshot.jpg
  Web Development/Task-1/Task Submission/Manasa Mohapatra/style.css
  Web Development/Task-1/Task Submission/Manasa Mohapatra/web link.txt
Labels: Approved, Awesome, Fully-responsive

#561 web development task 1 completed
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/css/style.css
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/image/movie time.jpg
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/image/myphoto.jpg
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/image/stockmarket.jpg
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/image/travelling.jpg
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/image/volley ball.jpg
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/index.html
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/link.txt
  Web Development/Task-1/Task Submission/Subham Sagar Pradhan/screenshot.jpeg
Labels: Approved, Fully-responsive

#546 Web dev task 1 completed
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/20230125_192351_2.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/I AM SIR.png
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/US-900x0-c-default.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/WallpaperDog-20546738.png
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/about.html
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/bkadp6.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/gallery.html
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/github.svg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa1.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa10.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa11.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa12.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa13.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa2.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa3.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa4.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa5.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa6.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa7.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa8.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/imaaa9.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/index.html
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/insta.svg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/link.svg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/link.txt
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/meme2.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/meme3.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/meme4.jpg
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/songs.html
  Web Development/Task-1/Task Submission/Aumshuman Mohapatra/styles.css
Labels: Approved, Awesome, Fully-responsive

#543 web dev task 1 completed
  Web Development/Task-1/Task Submission/Adishree Srikumar/CSS/style.css
  Web Development/Task-1/Task Submission/Adishree Srikumar/image/adventure.jpg
  Web Development/Task-1/Task Submission/Adishree Srikumar/image/my photo.jpg
  Web Development/Task-1/Task Submission/Adishree Srikumar/image/odissi.jpg
  Web Development/Task-1/Task Submission/Adishree Srikumar/image/travelling.jpg
  Web Development/Task-1/Task Submission/Adishree Srikumar/image/waterfall.jpg
  Web Development/Task-1/Task Submission/Adishree Srikumar/index.html
  Web Development/Task-1/Task Submission/Adishree Srikumar/link.txt
  Web Development/Task-1/Task Submission/Adishree Srikumar/screenshot.png
Labels: Approved, Fully-responsive

#535 Web Development Task 1 completed
  Web Development/Task-1/Task Submission/Rahul Panda/Screenshot_2023-03-31-11-15-00-48.jpg
  Web Development/Task-1/Task Submission/Rahul Panda/Task 1
  Web Development/Task-1/Task Submission/Rahul Panda/index.html
  Web Development/Task-1/Task Submission/Rahul Panda/link.txt
  Web Development/Task-1/Task Submission/Rahul Panda/rahul.jpg
  Web Development/Task-1/Task Submission/Rahul Panda/style.css
Labels: Approved, Fully-responsive

#746 web dev task 3 completed
  Web Development/Task-1/Task Submission/Adyasha Guru/html/Screenshot (4).png
  Web Development/Task-1/Task Submission/Adyasha Guru/html/images/adyasha2.jpeg
  Web Development/Task-1/Task Submission/Adyasha Guru/html/images/reading.png
  Web Development/Task-1/Task Submission/Adyasha Guru/html/images/singing.jpg
  Web Development/Task-1/Task Submission/Adyasha Guru/html/images/travel.png
  Web Development/Task-1/Task Submission/Adyasha Guru/html/index.html
  Web Development/Task-1/Task Submission/Adyasha Guru/html/link.txt
  Web Development/Task-1/Task Submission/Adyasha Guru/html/style.css
Labels: Approved, Fully-responsive

#528 Web Development task 1 completed
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/.vs/Sairaj_Pattnaik/config/applicationhost.config
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/.vs/Sairaj_Pattnaik/v17/.suo
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/Image 1.jpg
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/Image 2.jpg
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/Image 3.jpg
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/Link.txt
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/My Image.jpg
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/NFS_Most Wanted.jpg
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/Sairaj_Pattnaik.sln
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/Screenshot.png
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/index.html
  Web Development/Task-1/Task Submission/Sairaj_Pattnaik/style.css
Labels: Approved, Fully-responsive

#539 week 2 task 1 completed
  Web Development/Task-1/Task Submission/oindrila/images/image.jpg
  Web Development/Task-1/Task Submission/oindrila/images/moon.jpg
  Web Development/Task-1/Task Submission/oindrila/images/sky.jpg
  Web Development/Task-1/Task Submission/oindrila/images/youtube.jpg
  Web Development/Task-1/Task Submission/oindrila/index.html
  Web Development/Task-1/Task Submission/oindrila/link.txt
  Web Development/Task-1/Task Submission/oindrila/webpage0405.png
Labels: Approved, Fully-responsive

#537 git web task 1 completed
  Web Development/Task-1/Task Submission/Ritika_Sathua/10928807126_c75098ebfe_n.jpg
  Web Development/Task-1/Task Submission/Ritika_Sathua/11174857204_cced708349_n.jpg
  Web Development/Task-1/Task Submission/Ritika_Sathua/11467551254_2e1ffed34b_n.jpg
  Web Development/Task-1/Task Submission/Ritika_Sathua/11467599266_e99d516716_m.jpg
  Web Development/Task-1/Task Submission/Ritika_Sathua/11467603726_2c301c093a_m.jpg
  Web Development/Task-1/Task Submission/Ritika_Sathua/Screenshot (1).png
  Web Development/Task-1/Task Submission/Ritika_Sathua/Screenshot (2).png
  Web Development/Task-1/Task Submission/Ritika_Sathua/index.html
  Web Development/Task-1/Task Submission/Ritika_Sathua/link.txt
  Web Development/Task-1/Task Submission/Ritika_Sathua/style.css
  index.html
  style.css
Labels: Approved, Fully-responsive

#527 git week 2 task 1 completed
  Web Development/Task-1/Task Submission/Swapnil Roy/Screenshot.png
  Web Development/Task-1/Task Submission/Swapnil Roy/images/UIUX.jpg
  Web Development/Task-1/Task Submission/Swapnil Roy/images/game-development.avif
  Web Development/Task-1/Task Submission/Swapnil Roy/images/gaming.jpg
  Web Development/Task-1/Task Submission/Swapnil Roy/images/travel.jpg
  Web Development/Task-1/Task Submission/Swapnil Roy/index.html
  Web Development/Task-1/Task Submission/Swapnil Roy/link.txt
  Web Development/Task-1/Task Submission/Swapnil Roy/style.css
Labels: Approved, Awesome, Fully-responsive

#519 task 1 of web d completed
  Web Development/Task-1/Task Submission/aditya kumar/github.svg
  Web Development/Task-1/Task Submission/aditya kumar/index.html
  Web Development/Task-1/Task Submission/aditya kumar/insta.svg
  Web Development/Task-1/Task Submission/aditya kumar/link.svg
  Web Development/Task-1/Task Submission/aditya kumar/link.txt
  Web Development/Task-1/Task Submission/aditya kumar/pic.jpg
  Web Development/Task-1/Task Submission/aditya kumar/screenshot.png
  Web Development/Task-1/Task Submission/aditya kumar/style.css
Labels: Approved, Fully-responsive

#526 web dev task 1 completed
  Web Development/Task-1/Task Submission/Swastideepa Dash/css/style.css
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/ME.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me2.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me3.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me4.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me5.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me6.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me7.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/images/me8.jpeg
  Web Development/Task-1/Task Submission/Swastideepa Dash/index.html
  Web Development/Task-1/Task Submission/Swastideepa Dash/link.txt
  Web Development/Task-1/Task Submission/Swastideepa Dash/swastiscreenshot.png
Labels: Approved, Fully-responsive

#525 web dev task 1 complete
  Web Development/Task-1/Task Submission/samira/images/01212022-1047259374-coding-classes_scanrail.png
  Web Development/Task-1/Task Submission/samira/images/16158817.png
  Web Development/Task-1/Task Submission/samira/images/GettyImages-942494908-06ddf35dd0dc476fbf73f11b5e978e74.png
  Web Development/Task-1/Task Submission/samira/images/anushkasharma1602328437.png
  Web Development/Task-1/Task Submission/samira/images/ball.png
  Web Development/Task-1/Task Submission/samira/images/mount.png
  Web Development/Task-1/Task Submission/samira/images/night.png
  Web Development/Task-1/Task Submission/samira/images/samira.png
  Web Development/Task-1/Task Submission/samira/images/scenery.png
  Web Development/Task-1/Task Submission/samira/images/sketches-can-be-made-any-drawing-medium-term-most-often-applied-to-graphic-work-executed-dry-such-as-silverpoint-173560100.png
  Web Development/Task-1/Task Submission/samira/index.html
  Web Development/Task-1/Task Submission/samira/link.txt
  Web Development/Task-1/Task Submission/samira/screenshot.png
  Web Development/Task-1/Task Submission/samira/style.css
Labels: Approved, Fully-responsive

#524 web development task completed
  Web Development/Task-1/Task Submission/Supreethi/Images/Photo .jpg
  Web Development/Task-1/Task Submission/Supreethi/Images/Photo1.png
  Web Development/Task-1/Task Submission/Supreethi/Images/Picture.jpg
  Web Development/Task-1/Task Submission/Supreethi/Images/Picture1.png
  Web Development/Task-1/Task Submission/Supreethi/Images/amg 1.png
  Web Development/Task-1/Task Submission/Supreethi/Images/amg.jpg
  Web Development/Task-1/Task Submission/Supreethi/Images/butterfly 1.png
  Web Development/Task-1/Task Submission/Supreethi/Images/butterfly.jpg
  Web Development/Task-1/Task Submission/Supreethi/Images/swift 1.png
  Web Development/Task-1/Task Submission/Supreethi/Images/swift.jpg
  Web Development/Task-1/Task Submission/Supreethi/Images/taylor 1.png
  Web Development/Task-1/Task Submission/Supreethi/Images/taylor.jpg
  Web Development/Task-1/Task Submission/Supreethi/css/styles.css
  Web Development/Task-1/Task Submission/Supreethi/index.html
  Web Development/Task-1/Task Submission/Supreethi/link.txt
  Web Development/Task-1/Task Submission/Supreethi/screenshot.png
Labels: Approved, Fully-responsive

#523 webdev task 1 completed
  Web Development/Task-1/Task Submission/Pratyasha_Panda/css/styles.css
  Web Development/Task-1/Task Submission/Pratyasha_Panda/favicon.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/images/flower.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/images/green.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/images/laptop.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/images/me.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/images/nebula.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/images/pratyasha2.png
  Web Development/Task-1/Task Submission/Pratyasha_Panda/index.html
  Web Development/Task-1/Task Submission/Pratyasha_Panda/link.txt
  Web Development/Task-1/Task Submission/Pratyasha_Panda/screenshot.png
Labels: Approved, Fully-responsive

#522 webdev task1 completed
  Web Development/Task-1/Task Submission/priyadarshini muduli/images/g1.jpg
  Web Development/Task-1/Task Submission/priyadarshini muduli/images/g2.jpg
  Web Development/Task-1/Task Submission/priyadarshini muduli/images/g3.jpg
  Web Development/Task-1/Task Submission/priyadarshini muduli/images/interest.jpg
  Web Development/Task-1/Task Submission/priyadarshini muduli/images/me2.jpg
  Web Development/Task-1/Task Submission/priyadarshini muduli/images/th.png
  Web Development/Task-1/Task Submission/priyadarshini muduli/index.html
  Web Development/Task-1/Task Submission/priyadarshini muduli/link.txt.txt
  Web Development/Task-1/Task Submission/priyadarshini muduli/screenshot.png
  Web Development/Task-1/Task Submission/priyadarshini muduli/style.css
  Web Development/Task-1/Task Submission/priyadarshini muduli/test.exe
Labels: Approved, Fully-responsive

#688 Web Dev W2T1 completed
  Web Development/Task-1/Task Submission/Spandan Tripathy/About.html
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/220716-A-AB787-325.jpeg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/Discord-removebg-preview.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/Discord.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/IMG-20230322-WA0343.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/IMG_8608.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/IMG_8859 2.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/PXL_20230306_113849347.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/PXL_20230307_072813375.PORTRAIT.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/google-mail-icon-logo-isolated-on-transparent-background-free-vector.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/jIIOkJGRBVZa9P1XO-17QXK6KVPRMxj5_vIkbCTTjos.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/learn-code-programming-language-website-260nw-1192247899.webp
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/png-transparent-video-game-development-computer-icons-video-game-developer-design.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/pngwing.com.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/sm_5b072d393d61e-removebg-preview.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/sm_5b072d393d61e.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/steam-removebg-preview.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Images/steam.jpg
  Web Development/Task-1/Task Submission/Spandan Tripathy/Link.txt
  Web Development/Task-1/Task Submission/Spandan Tripathy/ScreenShot1.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/Screenshot 2.png
  Web Development/Task-1/Task Submission/Spandan Tripathy/index.html
Labels: Approved, Fully-responsive

#683 Web Dev: Task 1 completed
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/background.png
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/img1.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/img2.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/img3.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/img4.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/img5.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/img6.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/logo.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/img/user.jpg
  Web Development/Task-1/Task Submission/Sriyansh Dash/index.html
  Web Development/Task-1/Task Submission/Sriyansh Dash/screenshot of website.png
  Web Development/Task-1/Task Submission/Sriyansh Dash/style.css
  Web Development/Task-1/Task Submission/Sriyansh Dash/url of site.txt
Labels: Approved, Fully-responsive

#744 Web dev task 1
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/055c28db-7eb5-4eb5-8c9f-8e9d6f2db42d.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/18193d9c-632c-47b8-be69-6c5d69f08fe7.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/54ecc3f4-f3eb-4c6f-9690-1e220ee7c0b7.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/689911a9-9b85-4559-a004-9440dae41cd0.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/700236f2-5e46-4133-9cd1-9b3d242482b9.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/849da13c-dc56-44c6-8d08-5ebbc1b8fa72.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/Link.txt/httpsaadiiik.github.ioAditya-Kunwar.txt
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/OIP.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/d3f9c67b-5131-4d99-9272-f30bf333a594.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/d4f6dbe6-4e2b-4d2c-a676-8c12e9eb85c5.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/e6b06c99-ab69-4d5d-9e4a-9b47df94076d.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/IMAGES/e7b9d741-6821-4dd9-a9f2-9a232eb6b30b.jpg
  Web Development/Task-1/Task Submission/Aditya Kunwar/Link.txt/link.txt
  Web Development/Task-1/Task Submission/Aditya Kunwar/index.html
Labels: Approved, Fully-responsive

#521 Web development task-1 completed
  Web Development/Task-1/Task Submission/Ronesh Tarenia/index.html
  Web Development/Task-1/Task Submission/Ronesh Tarenia/link.txt
  Web Development/Task-1/Task Submission/Ronesh Tarenia/programming-skills.png
  Web Development/Task-1/Task Submission/Ronesh Tarenia/roimage.jpg
  Web Development/Task-1/Task Submission/Ronesh Tarenia/screenshot.png
  Web Development/Task-1/Task Submission/Ronesh Tarenia/style.css
Labels: Approved, Fully-responsive

#540 git task 1 Web Dev completed
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/Screenshot.png
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/index.html
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/link.txt
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/about me.jpeg
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/background.jpeg
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/gallary1.webp
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/gallary2.webp
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/gallary3.webp
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/header background.jpeg
  Web Development/Task-1/Task Submission/Ashish Kumar Sahoo/sample/my interest.webp
Labels: Approved, Fully-responsive

#578 Web development task-1 completed
  Web Development/Task-1/Task Submission/Kishor kumar sahu/1.png
  Web Development/Task-1/Task Submission/Kishor kumar sahu/3.jpg
  Web Development/Task-1/Task Submission/Kishor kumar sahu/4.png
  Web Development/Task-1/Task Submission/Kishor kumar sahu/index.html
  Web Development/Task-1/Task Submission/Kishor kumar sahu/link.txt
  Web Development/Task-1/Task Submission/Kishor kumar sahu/screenshot.png
  Web Development/Task-1/Task Submission/Kishor kumar sahu/style.css
Labels: Approved, Fully-responsive

#690 completed web task 1
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/arj.jpg
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/beserk.jpg
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/chess2.jpg
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/game develop.png
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/game develop.webp
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/gd2.webp
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/github.png
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/insta.png
  Web Development/Task-1/Task Submission/Aryaman Jena/assets/linkedin-logo-3.png
  Web Development/Task-1/Task Submission/Aryaman Jena/index.html
  Web Development/Task-1/Task Submission/Aryaman Jena/link.txt
  Web Development/Task-1/Task Submission/Aryaman Jena/screenshot.png
  Web Development/Task-1/Task Submission/Aryaman Jena/style.css
Labels: Approved, Fully-responsive

#662 web dev task 1 completed
  Web Development/Task-1/Task Submission/Jagadish Dash/Screenshot 2023-04-01 200947.png
  Web Development/Task-1/Task Submission/Jagadish Dash/cyber.png
  Web Development/Task-1/Task Submission/Jagadish Dash/eni.png
  Web Development/Task-1/Task Submission/Jagadish Dash/github.png
  Web Development/Task-1/Task Submission/Jagadish Dash/index.html
  Web Development/Task-1/Task Submission/Jagadish Dash/insta.png
  Web Development/Task-1/Task Submission/Jagadish Dash/intrest.png
  Web Development/Task-1/Task Submission/Jagadish Dash/link.txt
  Web Development/Task-1/Task Submission/Jagadish Dash/style.css
  Web Development/Task-1/Task Submission/Jagadish Dash/webD.png
Labels: Approved, Fully-responsive

#643 https://rajatkumarpadhi.github.io/rajat-kumar-padhi.github.io/
  Web Development/Task-1/Task Submission/rajat kumar padhi/AP_toy_story_ml_141107_16x9t_992.jpg
  Web Development/Task-1/Task Submission/rajat kumar padhi/Buzz_Lightyear.png
  Web Development/Task-1/Task Submission/rajat kumar padhi/img1.jpeg
  Web Development/Task-1/Task Submission/rajat kumar padhi/img2.jpeg
  Web Development/Task-1/Task Submission/rajat kumar padhi/img3.jpeg
  Web Development/Task-1/Task Submission/rajat kumar padhi/index.html
  Web Development/Task-1/Task Submission/rajat kumar padhi/link.txt.txt
  Web Development/Task-1/Task Submission/rajat kumar padhi/style.css
Labels: Approved, Fully-responsive

#622 Web page made more responsive
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/anime.jpg
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/anime.png
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/anime_image.jpg
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/extra1.jpg
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/extra2.jpg
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/extra3.jpg
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/git_logo.png
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/gmail_logo.png
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/hackerrank_logo.png
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/index.html
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/insta_logo.png
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/link.txt
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/linkedin_logo.png
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/profile.jpg
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/style.css
  Web Development/Task-1/Task Submission/Deepak Kumar Dash/vssut.jpeg
Labels: Approved, Fully-responsive

#613 https://syedfaizanurrahman.github.io/
  Web Development/Task-1/Task Submission/Syedrahman/images/21606827-a-word-cloud-of-web-development-related-items (1).webp
  Web Development/Task-1/Task Submission/Syedrahman/images/21606827-a-word-cloud-of-web-development-related-items.webp
  Web Development/Task-1/Task Submission/Syedrahman/images/24793eb3-e8f8-4d92-8471-8ca63d1dfcd3.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/3c5ce30b-3ae6-40e4-8233-1d738288ea3a.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/6b1ec160-acd7-475d-b0ee-7f4c4877b5b7.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/7f86a31a-ac5e-49dd-b4d1-0e51e889b863.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/7fee392a-2d46-4601-93d1-0294c1a4be37.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/99319281-9958-45e2-b156-210d23b4e87c.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/BGMI-B.webp
  Web Development/Task-1/Task Submission/Syedrahman/images/MV5BMDI3ZDY4MDgtN2U2OS00Y2YzLWJmZmYtZWMzOTM3YWFjYmUyXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/Naruto.webp
  Web Development/Task-1/Task Submission/Syedrahman/images/Valorant-Agents.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/anime-anime-boys-jujutsu-kaisen-yuji-itadori-sakuna-hd-wallpaper-preview.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/e61cd4e6-ce4a-442f-af7e-51aef5aef6dc.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/istockphoto-1254565557-612x612.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/wallhaven-zygeko (1).jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/wallhaven-zygeko.jpg
  Web Development/Task-1/Task Submission/Syedrahman/images/wp9666531.webp
  Web Development/Task-1/Task Submission/Syedrahman/index.html
  Web Development/Task-1/Task Submission/Syedrahman/link.txt
Labels: Approved, Fully-responsive

#609 web-dev task completed
  Web Development/Task-1/Task Submission/SIYA_AGRAWAL/LINK.txt
  Web Development/Task-1/Task Submission/SIYA_AGRAWAL/WhatsApp Image 2023-03-31 at 20.14.47.jpeg
  Web Development/Task-1/Task Submission/SIYA_AGRAWAL/index.html
  Web Development/Task-1/Task Submission/SIYA_AGRAWAL/siya180803.github.io_portfolio_.png
Labels: Approved, Fully-responsive

#596 web dev task 1 completed
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/WhatsApp1 Image.jpeg
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/camera.jpg
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/digital paint.jpg
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/index2.html
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/jyotir934.github.io_(iPhone SE).png
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/link.txt
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/nature.jpg
  Web Development/Task-1/Task Submission/Jyoti Ranjan Moharana/web-development.webp
Labels: Approved, Fully-responsive

#595 Task 1 of wed d completed
  Web development/Task1/Rohit Dash/1.jpg
  Web development/Task1/Rohit Dash/2.jpg
  Web development/Task1/Rohit Dash/3.jpg
  Web development/Task1/Rohit Dash/34.jpg
  Web development/Task1/Rohit Dash/4.jpg
  Web development/Task1/Rohit Dash/AIML-1 (1).jpg
  Web development/Task1/Rohit Dash/Index.html.html
  Web development/Task1/Rohit Dash/Link.txt
  Web development/Task1/Rohit Dash/SAVE_20230331_224403.jpg
  Web development/Task1/Rohit Dash/Wbd.jpg
  Web development/Task1/Rohit Dash/bk6.webp
  Web development/Task1/Rohit Dash/int3.png
  Web development/Task1/Rohit Dash/style.css
Labels: Approved, Fully-responsive

#536 Web task 1 completed
  Web Development/Task-1/Task Submission/Kumar_Piyush/Screenshot_2023-03-31_00-49-47.png
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/145807.png
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/5968534.png
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/Myimage.jpeg
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/coding-courses.png
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/giphy.gif
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/img1.jpg
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/img12.jpg
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/img4.png
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/instagram.png
  Web Development/Task-1/Task Submission/Kumar_Piyush/images/milky-way-2695569__480.jpg
  Web Development/Task-1/Task Submission/Kumar_Piyush/index.css
  Web Development/Task-1/Task Submission/Kumar_Piyush/index.html
  Web Development/Task-1/Task Submission/Kumar_Piyush/mylink.txt
Labels: Approved, Fully-responsive

#700 Webpage made more responsive
  Open_Source/Task-1/Arjun_Murmu.txt
  Web Development/Task-1/Task Submission/Arjun Murmu/arjun.jpg
  Web Development/Task-1/Task Submission/Arjun Murmu/dance.jpg
  Web Development/Task-1/Task Submission/Arjun Murmu/facebook.webp
  Web Development/Task-1/Task Submission/Arjun Murmu/fr1.jpg
  Web Development/Task-1/Task Submission/Arjun Murmu/fr2.jpg
  Web Development/Task-1/Task Submission/Arjun Murmu/fr3.jpg
  Web Development/Task-1/Task Submission/Arjun Murmu/github.png
  Web Development/Task-1/Task Submission/Arjun Murmu/hac.png
  Web Development/Task-1/Task Submission/Arjun Murmu/index.html
  Web Development/Task-1/Task Submission/Arjun Murmu/insta_logo.png
  Web Development/Task-1/Task Submission/Arjun Murmu/link.txt
  Web Development/Task-1/Task Submission/Arjun Murmu/linkedin_logo.png
  Web Development/Task-1/Task Submission/Arjun Murmu/mmr.jpg
  Web Development/Task-1/Task Submission/Arjun Murmu/style.css
Labels: Approved

#692 Blog created
  Web Development/Task-1/Task Submission/Lipsa Garud/anime.png
  Web Development/Task-1/Task Submission/Lipsa Garud/anime_image.jpg
  Web Development/Task-1/Task Submission/Lipsa Garud/extra1.jpg
  Web Development/Task-1/Task Submission/Lipsa Garud/extra2.jpg
  Web Development/Task-1/Task Submission/Lipsa Garud/extra3.jpg
  Web Development/Task-1/Task Submission/Lipsa Garud/git_logo.png
  Web Development/Task-1/Task Submission/Lipsa Garud/gmail_logo.png
  Web Development/Task-1/Task Submission/Lipsa Garud/hackerrank_logo.png
  Web Development/Task-1/Task Submission/Lipsa Garud/index.html
  Web Development/Task-1/Task Submission/Lipsa Garud/insta_logo.png
  Web Development/Task-1/Task Submission/Lipsa Garud/kabbadi.jpg
  Web Development/Task-1/Task Submission/Lipsa Garud/link.txt
  Web Development/Task-1/Task Submission/Lipsa Garud/linkedin_logo.png
  Web Development/Task-1/Task Submission/Lipsa Garud/profile.jpg
  Web Development/Task-1/Task Submission/Lipsa Garud/style.css
Labels: Approved

#681 Web Dev Task 1 Completed
  Web Development/Task-1/Task Submission/Pradeep Maharana/images/gallery.jpeg
  Web Development/Task-1/Task Submission/Pradeep Maharana/images/icons.png
  Web Development/Task-1/Task Submission/Pradeep Maharana/images/pradeep.jpg
  Web Development/Task-1/Task Submission/Pradeep Maharana/index.html
  Web Development/Task-1/Task Submission/Pradeep Maharana/link.txt
  Web Development/Task-1/Task Submission/Pradeep Maharana/screenshot.png
  Web Development/Task-1/Task Submission/Pradeep Maharana/style.css
Labels: Approved

#661 Web Development Task 1 Completed
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/Link.txt
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/Screenshot.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/blockchain-development-637e5922f13f0.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/contact.jpg
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/flutter5786.jpg
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/image9.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/blockchain-development-637e5922f13f0.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/flutter5786.jpg
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/image9.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/logo1.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/logo2.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/logo3.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/logo4.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/img/sunset love.jpg
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/index.html
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/logo1.jpg
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/logo1.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/logo2.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/logo3.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/logo4.png
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/style.css
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/sunset love.jpg
  Web Development/Task-1/Task Submission/Rohit Kumar Rout/wp6113061.jpg
Labels: Approved

#594 My induction
  Web Development/Task-1/Task Submission/Aryan Kar/Screenshot.PNG
  Web Development/Task-1/Task Submission/Aryan Kar/img.jpeg
  Web Development/Task-1/Task Submission/Aryan Kar/img1.jpeg
  Web Development/Task-1/Task Submission/Aryan Kar/img2.jpeg
  Web Development/Task-1/Task Submission/Aryan Kar/img3.jpeg
  Web Development/Task-1/Task Submission/Aryan Kar/index.html
  Web Development/Task-1/Task Submission/Aryan Kar/link.txt
  Web Development/Task-1/Task Submission/Aryan Kar/style.css
Labels: Approved

#593 web dev task 1 completed
  Web Development/Task-1/Task Submission/Swayanshu Behera/Screenshot1.png
  Web Development/Task-1/Task Submission/Swayanshu Behera/Screenshot2.png
  Web Development/Task-1/Task Submission/Swayanshu Behera/design.css
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/dp.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/github.png
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img1.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img2.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img3.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img4.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img5.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img6.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/img7.jpg
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/insta.png
  Web Development/Task-1/Task Submission/Swayanshu Behera/images/linkedin.png
  Web Development/Task-1/Task Submission/Swayanshu Behera/index.html
  Web Development/Task-1/Task Submission/Swayanshu Behera/link.txt
  Web Development/Task-1/Task Submission/Swayanshu Behera/readmore.css
  Web Development/Task-1/Task Submission/Swayanshu Behera/readmore.html
Labels: Approved

#590 Web dev task 1 completed
  Web Development/Task-1/Task Submission/Aditya Sahu/adi7910.github.io_.png
  Web Development/Task-1/Task Submission/Aditya Sahu/index.html
  Web Development/Task-1/Task Submission/Aditya Sahu/link.txt
  Web Development/Task-1/Task Submission/Aditya Sahu/r3.jpg
  Web Development/Task-1/Task Submission/Aditya Sahu/r4.jpg
  Web Development/Task-1/Task Submission/Aditya Sahu/r5.jpg
  Web Development/Task-1/Task Submission/Aditya Sahu/r6.jpg
  Web Development/Task-1/Task Submission/Aditya Sahu/r8.jpg
Labels: Approved
